"""
Local media library indexing and scene-candidate matching.

The library is generated by `scripts/build_media_metadata.py` and configured via:
  - LOCAL_MEDIA_LIBRARY_ROOT
  - LOCAL_MEDIA_METADATA_DIR (optional; defaults to <root>/metadata)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from urllib.parse import quote

from loguru import logger

from app.core.config import settings


def _tokenize(text: str) -> set[str]:
    token_chars: list[str] = []
    tokens: set[str] = set()
    for char in text.lower():
        if char.isalnum():
            token_chars.append(char)
        else:
            if len(token_chars) >= 3:
                tokens.add("".join(token_chars))
            token_chars = []
    if len(token_chars) >= 3:
        tokens.add("".join(token_chars))
    return tokens


def _concept_boost(scene_text: str, asset_tokens: set[str]) -> float:
    """Boost score when scene language implies a concept present in the asset."""
    scene = scene_text.lower()
    concept_map: list[tuple[list[str], list[str], float]] = [
        (["grew up", "childhood", "as a kid", "young"], ["baby", "child", "childhood", "mother", "mom", "family", "parent"], 3.2),
        (["study hard", "studied", "exam", "school", "college"], ["study", "student", "book", "books", "notebook", "library", "classroom"], 2.8),
        (["engineer", "engineering", "developer", "coding"], ["engineer", "developer", "coding", "code", "laptop", "computer", "software"], 2.6),
        (["graduation", "graduate", "degree"], ["graduation", "graduate", "diploma", "cap", "gown", "ceremony"], 3.0),
        (["job", "work", "office", "career"], ["work", "working", "office", "desk", "laptop", "computer", "meeting"], 2.3),
    ]
    total = 0.0
    for scene_terms, asset_terms, weight in concept_map:
        if not any(term in scene for term in scene_terms):
            continue
        if any(term in asset_tokens for term in asset_terms):
            total += weight
    return total


class LocalMediaLibraryService:
    def __init__(self) -> None:
        root = (settings.LOCAL_MEDIA_LIBRARY_ROOT or "").strip()
        self.library_root = Path(root).expanduser().resolve() if root else None
        metadata_dir = (settings.LOCAL_MEDIA_METADATA_DIR or "").strip()
        self.metadata_dir = (
            Path(metadata_dir).expanduser().resolve()
            if metadata_dir
            else (self.library_root / "metadata" if self.library_root else None)
        )
        self.manifest_path = self.metadata_dir / "library_manifest.json" if self.metadata_dir else None
        mount_path = (settings.LOCAL_MEDIA_LIBRARY_MOUNT_PATH or "/local-library").strip() or "/local-library"
        self.mount_path = mount_path if mount_path.startswith("/") else f"/{mount_path}"

        self._cache_manifest_mtime: float | None = None
        self._cache_assets: list[dict[str, Any]] = []

    def is_enabled(self) -> bool:
        return (
            self.library_root is not None
            and self.library_root.exists()
            and self.manifest_path is not None
            and self.manifest_path.exists()
        )

    def _load_assets(self) -> list[dict[str, Any]]:
        if not self.is_enabled():
            return []

        assert self.manifest_path is not None
        assert self.metadata_dir is not None
        assert self.library_root is not None

        try:
            manifest_mtime = self.manifest_path.stat().st_mtime
        except OSError:
            return []

        if self._cache_manifest_mtime == manifest_mtime:
            return self._cache_assets

        try:
            manifest = json.loads(self.manifest_path.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.warning(f"Failed to parse local media manifest: {exc}")
            return []

        output_dir_raw = str(manifest.get("output_dir") or "")
        output_dir = Path(output_dir_raw).expanduser().resolve() if output_dir_raw else self.metadata_dir
        assets: list[dict[str, Any]] = []

        for row in manifest.get("assets", []):
            metadata_rel = row.get("metadata_path")
            if not metadata_rel:
                continue
            metadata_path = Path(metadata_rel)
            if not metadata_path.is_absolute():
                metadata_path = output_dir / metadata_path
            if not metadata_path.exists():
                continue

            try:
                meta = json.loads(metadata_path.read_text(encoding="utf-8"))
            except Exception:
                continue

            relative_path = str(meta.get("relative_path") or "").strip()
            media_type = str(meta.get("media_type") or "").strip().lower()
            if not relative_path or media_type not in {"image", "video"}:
                continue

            media_path = (self.library_root / relative_path).resolve()
            try:
                media_path.relative_to(self.library_root)
            except Exception:
                continue
            if not media_path.exists():
                continue

            technical = meta.get("technical") or {}
            semantic = meta.get("semantic") or {}
            scores = semantic.get("scores") or {}
            timing = semantic.get("timing_recommendation") or {}
            encoded_rel = quote(relative_path, safe="/")
            public_url = f"{self.mount_path}/{encoded_rel}"
            query_parts = [
                str(semantic.get("subject") or "").strip(),
                str(semantic.get("action") or "").strip(),
                str(semantic.get("setting") or "").strip(),
            ]
            query = " ".join(part for part in query_parts if part) or str(relative_path)
            tags = [str(tag).lower() for tag in (semantic.get("tags") or [])]

            assets.append({
                "asset_id": str(meta.get("asset_id") or relative_path),
                "relative_path": relative_path,
                "media_type": media_type,
                "type": "local_video" if media_type == "video" else "local_image",
                "asset_url": public_url,
                "thumbnail_url": public_url,
                "source_provider": "local_library",
                "width": int(technical.get("width") or 0),
                "height": int(technical.get("height") or 0),
                "duration_seconds": float(technical.get("duration_seconds") or 0) if technical.get("duration_seconds") else None,
                "orientation": str(technical.get("orientation") or "unknown"),
                "query": query,
                "subject": str(semantic.get("subject") or ""),
                "setting": str(semantic.get("setting") or ""),
                "action": str(semantic.get("action") or ""),
                "mood": str(semantic.get("mood") or ""),
                "best_use": str(timing.get("best_use") or "body"),
                "suggested_scene_duration_seconds": float(timing.get("suggested_scene_duration_seconds") or 0) if timing.get("suggested_scene_duration_seconds") else None,
                "hook_strength": float(scores.get("hook_strength") or 0.5),
                "science_relevance": float(scores.get("science_relevance") or 0.5),
                "clarity_for_mobile": float(scores.get("clarity_for_mobile") or 0.5),
                "contains_text_overlay_risk": bool((semantic.get("safety") or {}).get("contains_text_overlay_risk", False)),
                "tags": tags,
                "token_index": _tokenize(
                    " ".join([
                        relative_path,
                        str(meta.get("original_relative_path") or ""),
                        query,
                        str(semantic.get("subject") or ""),
                        str(semantic.get("setting") or ""),
                        str(semantic.get("action") or ""),
                        str(semantic.get("mood") or ""),
                        " ".join(tags),
                    ])
                ),
            })

        self._cache_manifest_mtime = manifest_mtime
        self._cache_assets = assets
        logger.info(f"Loaded local media library index: {len(assets)} assets")
        return assets

    @staticmethod
    def _scene_intent(scene: dict, idx: int, total: int) -> str:
        start = float(scene.get("start_time_seconds") or 0)
        if start <= 3.0:
            return "hook"
        if total > 1 and idx >= total - 1:
            return "outro"
        return "body"

    @staticmethod
    def _score_asset(scene: dict, asset: dict, scene_intent: str) -> float:
        scene_text = " ".join([
            str(scene.get("anchor_word") or ""),
            str(scene.get("transcript_excerpt") or ""),
        ])
        scene_tokens = _tokenize(scene_text)
        overlap = len(scene_tokens.intersection(asset.get("token_index", set())))
        anchor = str(scene.get("anchor_word") or "").strip().lower()
        anchor_hit = 1.0 if anchor and anchor in asset.get("token_index", set()) else 0.0

        score = 0.0
        score += overlap * 3.2
        score += anchor_hit * 3.0
        score += _concept_boost(scene_text, asset.get("token_index", set()))
        score += float(asset.get("science_relevance") or 0.5) * 2.0
        score += float(asset.get("clarity_for_mobile") or 0.5) * 1.8
        score += float(asset.get("hook_strength") or 0.5) * (2.0 if scene_intent == "hook" else 1.0)
        if asset.get("media_type") == "video":
            # Default preference: motion assets usually perform better in reels.
            score += 2.4
        if str(asset.get("best_use") or "") == scene_intent:
            score += 1.4
        if str(asset.get("orientation") or "") == "portrait":
            score += 1.0
        if asset.get("contains_text_overlay_risk"):
            score -= 0.7
        if overlap == 0 and anchor_hit == 0:
            # Avoid unrelated picks floating to the top on generic metadata.
            score -= 2.0

        target_dur = float(
            max(
                0.8,
                float(scene.get("end_time_seconds") or 0) - float(scene.get("start_time_seconds") or 0),
            )
        )
        suggested = asset.get("suggested_scene_duration_seconds")
        if suggested:
            delta = abs(float(suggested) - target_dur)
            score += max(0.0, 1.2 - min(delta, 2.0) * 0.6)

        return round(score, 4)

    def get_scene_candidates(
        self,
        scenes: list[dict],
        max_candidates_per_scene: int = 4,
    ) -> dict[str, list[dict]]:
        assets = self._load_assets()
        if not assets:
            return {scene["scene_id"]: [] for scene in scenes}

        results: dict[str, list[dict]] = {}
        total = max(len(scenes), 1)
        for idx, scene in enumerate(scenes):
            scene_id = scene["scene_id"]
            scene_intent = self._scene_intent(scene, idx, total)
            ranked: list[dict[str, Any]] = []
            for asset in assets:
                score = self._score_asset(scene, asset, scene_intent)
                ranked.append({
                    "candidate_id": f"local-{asset['asset_id']}-{scene_id}",
                    "type": asset["type"],
                    "thumbnail_url": asset["thumbnail_url"],
                    "asset_url": asset["asset_url"],
                    "source_provider": asset["source_provider"],
                    "width": asset["width"],
                    "height": asset["height"],
                    "duration_seconds": asset["duration_seconds"],
                    "query": asset["query"],
                    "score": score,
                })
            ranked.sort(key=lambda row: row["score"], reverse=True)
            deduped: dict[str, dict[str, Any]] = {}
            for candidate in ranked:
                deduped.setdefault(candidate["asset_url"], candidate)
            results[scene_id] = list(deduped.values())[:max_candidates_per_scene]
        return results

    def list_assets(self, limit: int = 1000) -> list[dict[str, Any]]:
        """Return local-library assets as candidate rows for manual scene selection."""
        assets = self._load_assets()
        if not assets:
            return []

        rows: list[dict[str, Any]] = []
        for asset in assets:
            rows.append({
                "candidate_id": f"local-{asset['asset_id']}",
                "type": asset["type"],
                "thumbnail_url": asset["thumbnail_url"],
                "asset_url": asset["asset_url"],
                "source_provider": asset["source_provider"],
                "width": asset["width"],
                "height": asset["height"],
                "duration_seconds": asset["duration_seconds"],
                "query": f"{asset['query']} ({asset['relative_path']})",
                "score": round(
                    float(asset.get("hook_strength", 0.5))
                    + float(asset.get("science_relevance", 0.5))
                    + float(asset.get("clarity_for_mobile", 0.5)),
                    4,
                ),
            })

        # Default browse order: videos first, then higher quality signals.
        rows.sort(
            key=lambda row: (
                0 if row.get("type") == "local_video" else 1,
                -float(row.get("score", 0.0)),
            )
        )
        return rows[: max(1, limit)]
