"""create_social_posts_table

Revision ID: 17ad66eb9fbe
Revises: add_slug_to_episodes
Create Date: 2026-02-18 16:23:04.351036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17ad66eb9fbe'
down_revision: Union[str, Sequence[str], None] = 'add_slug_to_episodes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cron_runs_job_name'), table_name='cron_runs')
    op.drop_index(op.f('idx_cron_runs_run_date'), table_name='cron_runs')
    op.drop_table('cron_runs')
    op.drop_index(op.f('ix_waitlist_emails_email'), table_name='waitlist_emails')
    op.drop_index(op.f('ix_waitlist_emails_id'), table_name='waitlist_emails')
    op.drop_table('waitlist_emails')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.alter_column('papers', 'is_used_in_episode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_papers_has_full_text'), table_name='papers')
    op.drop_index(op.f('idx_papers_quality_score'), table_name='papers')
    op.create_index(op.f('ix_papers_has_full_text'), 'papers', ['has_full_text'], unique=False)
    op.create_index(op.f('ix_papers_quality_score'), 'papers', ['quality_score'], unique=False)
    op.drop_index(op.f('idx_podcast_episodes_slug'), table_name='podcast_episodes')
    op.create_index(op.f('ix_podcast_episodes_slug'), 'podcast_episodes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_episodes_slug'), table_name='podcast_episodes')
    op.create_index(op.f('idx_podcast_episodes_slug'), 'podcast_episodes', ['slug'], unique=True)
    op.drop_index(op.f('ix_papers_quality_score'), table_name='papers')
    op.drop_index(op.f('ix_papers_has_full_text'), table_name='papers')
    op.create_index(op.f('idx_papers_quality_score'), 'papers', ['quality_score'], unique=False)
    op.create_index(op.f('idx_papers_has_full_text'), 'papers', ['has_full_text'], unique=False)
    op.alter_column('papers', 'is_used_in_episode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('contact_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_messages_pkey'))
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('subscription_status', sa.TEXT(), server_default=sa.text("'trial'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    op.create_table('waitlist_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_notified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('waitlist_emails_pkey'))
    )
    op.create_index(op.f('ix_waitlist_emails_id'), 'waitlist_emails', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_emails_email'), 'waitlist_emails', ['email'], unique=True)
    op.create_table('cron_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cron_runs_pkey'))
    )
    op.create_index(op.f('idx_cron_runs_run_date'), 'cron_runs', ['run_date'], unique=False)
    op.create_index(op.f('idx_cron_runs_job_name'), 'cron_runs', ['job_name'], unique=False)
    # ### end Alembic commands ###
